### PR TITLE
Removed unused keyword "Delete"

### PR DESCRIPTION
**Pull request by thareh**
If it hasn't been used yet it probably won't? =P

### CODE REVIEW

**Comment by woollybah** [comment]
Actually... `Delete` is used a lot - by me!

It's called when an Object is about to be collected by the Garbage Collector, during "finalisation" - the default implementation is to not actually do anything, but you can implement/override your own in order to do things like free up un-managed memory.

**Comment by woollybah** [comment]
Here's an example of one : 
https://github.com/bmx-ng/brl.mod/blob/823964e74bcbb8187fd1938df8f8cfd155937c59/audiosample.mod/audiosample.bmx#L49-L51

:o)

**Comment by HurryStarfish** [comment]
This kind of method is called a _finalizer_, in case you want to look up more info on this.

**Comment by GWRon** [comment]
Do not forget the real issue about it: that the documentation in that one file states it is not uses yet and reserved for later...

**Comment by thareh** [comment]
Roger that! I was misguided by the documentation, I'll see if I can rewrite it and add a proper example :)

**Pull request closed without merging**
