### PR TITLE
Possible WriteLine improvement

### PR DESCRIPTION
**Pull request by thareh**
Good day,

Is this perhaps a better way of doing WriteLine?

My thinking is that this requires one Write call instead of two which would be beneficial if the stream is over the internet for example.

Anyway, just a thought.

### CODE REVIEW

**Comment by thareh** [comment]
Saw now that it may just as well use the WriteString function with "~r~n" added, if this is a good idea that is.

**Comment by GWRon** [comment]
Your change replaces a "second Write command with a constant parameter" (the newline `\r\n`) with an additionally created string (a new GC allocation).
Depending on the "string" this means allocating either some bytes ... or possibly even more.

Dunno if that "costs less" so to say.

**Comment by GWRon** [comment]
Your first commit: https://github.com/bmx-ng/brl.mod/pull/314/commits/ae2c15ed7151b9a9ce9f0a61fde5c65947c98f53
looks indeed like it fixes some missed/overlooked thing (as else the "length" variable would not be of any use in that method).

**Comment by thareh** [comment]
Nevermind, I'm probably just rambling. The utf8 fix is in another PR. Cheers!

**Pull request closed without merging**
