### PR TITLE
[Brl.IO] Add GetUserDir() and GetWriteDir()

### PR DESCRIPTION
**Pull request by GWRon**

### CODE REVIEW

**Comment by woollybah** [comment]
PHYSFS_getUserDir is deprecated since 2.1

**Comment by GWRon** [comment]
Will revise. Could add getSearchPath().

**Comment by woollybah** [comment]
I've just pushed some changes I'd been working on.

**Comment by GWRon** [comment]
Just saw it. Maybe you could add getsearchpath() on your own.

Could be something in the lines of

```
BBString * bmx_PHYSFS_getSearchPath() {
    BBString* ReturnResult = &bbEmptyString;
    char **rc = PHYSFS_getSearchPath();

    if (rc == NULL)
        printf("Failure. reason: %s.\n", PHYSFS_getLastError());
    else
    {
        int dir_count;
        char **i;
        for (i = rc, dir_count = 0; *i != NULL; i++, dir_count++)
            ReturnResult = bbStringConcat(ReturnResult, bbStringFromUTF8String(*i));

        printf("\n total (%d) directories.\n", dir_count);
        PHYSFS_freeList(rc);
        
       return ReturnResult;
    } /* else */
    return &bbEmptyString;
}
```

**Pull request closed without merging**
