### PR TITLE
show intrinsic element values and array values in the debugger

### PR DESCRIPTION
**Pull request by SRSSoftware**
Hiya,

This little modification shows the element values of the intrinsic types in the debugger.
Also you should now be able expand and show the values of arrays in the debugger too.

### CODE REVIEW

**Comment by woollybah** [comment]
I'm not sure removing the bbGCValidate() check is a good idea.
I would expect the debugger to fall over when it tried to handle real pointers.

**Comment by woollybah** [comment]
See #30, for the issue with displaying array contents. ;-)

**Comment by SRSSoftware** [comment]
Ok cool, I did wonder what the other check was for. So after your fix we can view arrays in the debugger, or not at all?
Its also nice to see the element values of the intrinsics in the debugger too :-)

**Comment by woollybah** [comment]
#30 enables viewing arrays in the debugger (since the pointers/references are now correctly detected as array objects).

If you remove the  change to the bbGCValidate line, I'll accept this :-)

**Comment by SRSSoftware** [comment]
Nice one! thanks :-)

**Pull request merged**
