### PR TITLE
Added compressed textures tweak to glmax2d, MSAA to glgraphics

### PR DESCRIPTION
**Pull request by markcwm**
This is the same tweaks I applied to BRL Maxmods, I've diff'd them and I'm sure it's just my tweaks onto latest commit 8.5.19. I went back to v0.81 and applied the tweak to all higher versions except v0.98 as it wouldn't build in Linux.

### CODE REVIEW

**Comment by woollybah** [comment]
Hallo :-)

I'm not sure I can take this, because I just can't see what's changed. It's says there are 974 file changes.
It might be easier simply to merge in your maxmods changes into the latest... by hand.

I'll have a look.

**Comment by markcwm** [comment]
Yeah, I understand it's a bit drastic, I thought this was the best way to do it, by providing many older versions, maybe I should just have a separate branch?

**Comment by GWRon** [comment]
Have all your changes in your branch ("feat_compressedtextures").

Update your branch to the latest of branch "master" (which you update with "bmx-ng/brl.mod"). You will get a load of conflicting files. These are the files having changes done by us while you updated your branch. These conflicts have to be solved by you (by hand). Means eg. in a diff view you select which part to keep "theirs" (us) or "ours" (yours).

At the end you have committable state consisting of your complete changes.

Now: if the changes affect multiple (brl.mod-)modules which can work separately then you could even commit them separately (for easier "reverting").

That required merge work by the authors of commits is what made GIT so special ... in SVN or others it was the repo owner who had to do the grunt work :-)

**Comment by GWRon** [comment]
Regarding 974 files: I assume (without having a close look) that somewhere in your commits you committed full files. Now when you needed to introduce the "meanwhile done in master" commits you end up replicating them. Which is why the diffs now show changes already being available in "master".

Another tip: With tools like `Meld` you could do a directory comparison:
- copy/export your patched repo into "brl.mod.markcwm" (or so)
- update the master branch of your original "brl.mod" clone
- create a new branch "feat_compressedtextures" in your "brl.mod" (the original repo clone)
- compare the changes "file by file" (they are marked if they differ) and bring in the desired changes
At the end the featured branch should only contain your needed changes - ready to commit.

Once the PR is accepted and changes are merged into master you can safely delete the "feat_compressedtextures" branch (locally and remote - from your github repo).
Avoid pushing changes to your fork's master. This will somewhen break your fork - eg if your PR is declined undoing all your changes in your fork can become problematic if other commits were done afterwards (so hard-reset is troublesome).

If you had multiple features added then you could have multiple branches:
- master (equals to official commit state)
- dev (your "bleeding edge" thing)
- feat_***, fix_*** branches playing with individual new stuff

If you want to have "all in one" version of the code (containing all the features and fixes which are not in "master" yet) then merge your changes of feat_*** and fix_*** branches into "dev". You can even update your various feat/fix branches to the latest master (and solve conflicts if there are some). Then you could merge in your branches into "dev".

Old but still of interest:
https://nvie.com/posts/a-successful-git-branching-model/

**Comment by woollybah** [comment]
The initial commit (in maxmods) changes 5 files. The further commit modifies one of those.
So in theory, the merge into here would only involve 5 files too :-)

**Comment by markcwm** [comment]
Okay, I'll close this and commit just the five files.

**Pull request closed without merging**
