### PR TITLE
Loader fix

### PR DESCRIPTION
**Pull request by thareh**
Sometimes a loader will accept a file that is in another format, this is my fix for that - perhaps there's a better way to do it?

### CODE REVIEW

**Comment by GWRon** [comment]
Shouldn't the loader just ... not return a TPixmap object?

**Comment by thareh** [comment]
Ah yes, seems SVG might be the culprit.

**Comment by thareh** [comment]
It seems the SVG-loader does return a pixmap even if the file is not a valid SVG file.

**Comment by GWRon** [comment]
The questions are:
- can there be multiple loaders for a specific image format? (eg 2 loaders for "png") ?
- what should happen if a loader cannot load the file they chose to "support"

**Comment by woollybah** [comment]
A "loader" should only return a TPixmap if it was able to do something with the data.
If there is a loader that isn't working like that, consider it a bug :)

When a loader returns a TPixmap, it stops looking for a loader, so if you have two loaders that *could* load something, the first one it finds will be the one it uses.

**Comment by GWRon** [comment]
Yeah the bugfix should happen in the loader which accidentally returns an tpixmap instance albeit it failed loading data properly

**Pull request closed without merging**
